import { BadgeCheck, Gift, HandHelping, LockKeyhole, Sparkles } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function TutorPerksPage() {
  const perks = trpc.mosaic.tutorPerks.useQuery();
  const claim = trpc.mosaic.claimTutorPerk.useMutation({ onSuccess: () => perks.refetch() });
  if (perks.isLoading || !perks.data) return <div className="app-loading"><div className="mosaic-mark">M</div><p>Loading Tutor Circle…</p></div>;
  return <main className="tutor-page"><header className="tutor-header"><a href="/" className="brand"><img src="/logo.png" alt="Mosaic Classroom" className="mosaic-mark" /><span>Mosaic<span>Classroom</span></span></a><div className="tutor-header__right"><span className="role-chip"><HandHelping size={14} />Tutor workspace</span><a href="/login/student" className="text-button">Student login</a><a href="/teacher" className="text-button">Educator view</a></div></header><section className="tutor-hero"><div><div className="eyebrow"><Sparkles size={14} />Tutor Circle</div><h1>Perks for the people who help learners keep going.</h1><p>Mentors can support a classroom without seeing private student profiles. Earn useful tools, planning time, and recognition as you show up.</p></div><div className="tutor-hero__badge"><BadgeCheck size={29} /><b>Mentor-safe access</b><small>Student names stay scoped to the educator’s classroom flow.</small></div></section><section className="tutor-content"><div className="tutor-content__heading"><div><div className="eyebrow">Available now</div><h2>Choose a perk to claim</h2></div><span className="status-pill status-pill--live">{perks.data.filter((perk) => perk.status === "available").length} available</span></div><div className="perk-grid">{perks.data.map((perk) => <article className={perk.status === "claimed" ? "perk-card perk-card--claimed" : "perk-card"} key={perk.id}><div className="perk-card__icon"><Gift size={21} /></div><div className="eyebrow">{perk.code}</div><h3>{perk.title}</h3><p>{perk.description}</p><button className="btn btn--student" disabled={perk.status === "claimed" || claim.isPending} onClick={() => claim.mutate({ id: perk.id })}>{perk.status === "claimed" ? "Claimed" : "Claim perk"}</button></article>)}</div><div className="tutor-privacy"><LockKeyhole size={17} /><span><b>What tutors can see</b><small>Assigned activities, group-level signals, and their own mentor notes.</small></span><span><b>What tutors cannot see</b><small>Another student’s personal profile, private analytics, or unrelated answers.</small></span></div></section></main>;
}
